CREATE TABLE IF NOT EXISTS associate (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    cpf CHAR(14) NOT NULL 
);

CREATE TABLE IF NOT EXISTS agenda (
    id SERIAL PRIMARY KEY,
    description TEXT NOT NULL
);